//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface IApplicationsClient {
    /**
     * ListApplications
     */
    listApplications(): Observable<ApplicationDto[]>;
    /**
     * RegisterApplication
     */
    registerApplication(request: RegisterApplicationRequest): Observable<ApplicationDto>;
}

@Injectable({
    providedIn: 'root'
})
export class ApplicationsClient implements IApplicationsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * ListApplications
     */
    listApplications(): Observable<ApplicationDto[]> {
        let url_ = this.baseUrl + "/api/applications";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processListApplications(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processListApplications(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ApplicationDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ApplicationDto[]>;
        }));
    }

    protected processListApplications(response: HttpResponseBase): Observable<ApplicationDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ApplicationDto[];
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * RegisterApplication
     */
    registerApplication(request: RegisterApplicationRequest): Observable<ApplicationDto> {
        let url_ = this.baseUrl + "/api/applications";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRegisterApplication(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRegisterApplication(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ApplicationDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ApplicationDto>;
        }));
    }

    protected processRegisterApplication(response: HttpResponseBase): Observable<ApplicationDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            result201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ApplicationDto;
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status === 409) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result409: any = null;
            result409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string;
            return throwException("A server side error occurred.", status, _responseText, _headers, result409);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface IDashboardClient {
    /**
     * GetDashboard
     * @param applicationId (optional) 
     */
    getDashboard(applicationId: string | null | undefined): Observable<DashboardDto>;
}

@Injectable({
    providedIn: 'root'
})
export class DashboardClient implements IDashboardClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * GetDashboard
     * @param applicationId (optional) 
     */
    getDashboard(applicationId: string | null | undefined): Observable<DashboardDto> {
        let url_ = this.baseUrl + "/api/dashboard?";
        if (applicationId !== undefined && applicationId !== null)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDashboard(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDashboard(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DashboardDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DashboardDto>;
        }));
    }

    protected processGetDashboard(response: HttpResponseBase): Observable<DashboardDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DashboardDto;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface IDbDurationsClient {
    /**
     * ListDbDurations
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listDbDurations(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse>;
}

@Injectable({
    providedIn: 'root'
})
export class DbDurationsClient implements IDbDurationsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * ListDbDurations
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listDbDurations(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse> {
        let url_ = this.baseUrl + "/api/db-durations?";
        if (applicationId !== undefined && applicationId !== null)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        if (take !== undefined && take !== null)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processListDbDurations(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processListDbDurations(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TelemetryListResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TelemetryListResponse>;
        }));
    }

    protected processListDbDurations(response: HttpResponseBase): Observable<TelemetryListResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TelemetryListResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface IErrorsClient {
    /**
     * ListErrors
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listErrors(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse>;
}

@Injectable({
    providedIn: 'root'
})
export class ErrorsClient implements IErrorsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * ListErrors
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listErrors(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse> {
        let url_ = this.baseUrl + "/api/errors?";
        if (applicationId !== undefined && applicationId !== null)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        if (take !== undefined && take !== null)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processListErrors(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processListErrors(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TelemetryListResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TelemetryListResponse>;
        }));
    }

    protected processListErrors(response: HttpResponseBase): Observable<TelemetryListResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TelemetryListResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface IPerformanceCountersClient {
    /**
     * GetPerformanceCounters
     * @param intervalMinutes (optional) 
     */
    getPerformanceCounters(intervalMinutes: number | null | undefined): Observable<PerformanceCountersDto>;
}

@Injectable({
    providedIn: 'root'
})
export class PerformanceCountersClient implements IPerformanceCountersClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * GetPerformanceCounters
     * @param intervalMinutes (optional) 
     */
    getPerformanceCounters(intervalMinutes: number | null | undefined): Observable<PerformanceCountersDto> {
        let url_ = this.baseUrl + "/api/performance-counters?";
        if (intervalMinutes !== undefined && intervalMinutes !== null)
            url_ += "intervalMinutes=" + encodeURIComponent("" + intervalMinutes) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPerformanceCounters(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPerformanceCounters(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<PerformanceCountersDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<PerformanceCountersDto>;
        }));
    }

    protected processGetPerformanceCounters(response: HttpResponseBase): Observable<PerformanceCountersDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PerformanceCountersDto;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface IRequestDurationsClient {
    /**
     * ListRequestDurations
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listRequestDurations(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse>;
}

@Injectable({
    providedIn: 'root'
})
export class RequestDurationsClient implements IRequestDurationsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * ListRequestDurations
     * @param applicationId (optional) 
     * @param take (optional) 
     */
    listRequestDurations(applicationId: string | null | undefined, take: number | null | undefined): Observable<TelemetryListResponse> {
        let url_ = this.baseUrl + "/api/request-durations?";
        if (applicationId !== undefined && applicationId !== null)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        if (take !== undefined && take !== null)
            url_ += "take=" + encodeURIComponent("" + take) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processListRequestDurations(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processListRequestDurations(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TelemetryListResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TelemetryListResponse>;
        }));
    }

    protected processListRequestDurations(response: HttpResponseBase): Observable<TelemetryListResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TelemetryListResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface ITelemetryClient {
    /**
     * IngestTelemetryEnvelope
     */
    ingestTelemetryEnvelope(envelope: TelemetryEnvelope): Observable<void>;
    /**
     * IngestTelemetry
     */
    ingestTelemetry(envelope: TelemetryEnvelope): Observable<void>;
}

@Injectable({
    providedIn: 'root'
})
export class TelemetryClient implements ITelemetryClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * IngestTelemetryEnvelope
     */
    ingestTelemetryEnvelope(envelope: TelemetryEnvelope): Observable<void> {
        let url_ = this.baseUrl + "/api/telemetry/envelopes";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(envelope);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processIngestTelemetryEnvelope(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIngestTelemetryEnvelope(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processIngestTelemetryEnvelope(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 202) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * IngestTelemetry
     */
    ingestTelemetry(envelope: TelemetryEnvelope): Observable<void> {
        let url_ = this.baseUrl + "/api/telemetry";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(envelope);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processIngestTelemetry(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIngestTelemetry(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processIngestTelemetry(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 202) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface ApplicationDto {
    id?: string;
    name?: string;
    environment?: string;
    siteName?: string;
    dsn?: string;
    isEnabled?: boolean;
    createdAt?: string;
    updatedAt?: string;
    description?: string | undefined;
}

export interface RegisterApplicationRequest {
    name?: string;
    environment?: string;
    siteName?: string;
    description?: string | undefined;
}

export interface DashboardDto {
    selectedApplicationId?: string | undefined;
    windowStart?: string;
    windowEnd?: string;
    applicationCount?: number;
    errorCount?: number;
    requests?: MetricSummaryDto;
    database?: MetricSummaryDto;
    sites?: SiteHealthDto[];
}

export interface MetricSummaryDto {
    count?: number;
    averageMs?: number;
    p95Ms?: number;
    maxMs?: number;
}

export interface SiteHealthDto {
    applicationId?: string;
    applicationName?: string;
    environment?: string;
    siteName?: string;
    status?: SiteHealthStatus;
    lastSeenAt?: string | undefined;
    errors24h?: number;
    requests24h?: MetricSummaryDto;
    database24h?: MetricSummaryDto;
}

export enum SiteHealthStatus {
    Healthy = "Healthy",
    Degraded = "Degraded",
    Offline = "Offline",
}

export interface TelemetryListResponse {
    items?: TelemetryEventDto[];
    count?: number;
    take?: number;
}

export interface TelemetryEventDto {
    id?: string;
    applicationId?: string;
    applicationName?: string;
    environment?: string;
    siteName?: string;
    signal?: TelemetrySignal;
    occurredAt?: string;
    severity?: string;
    message?: string | undefined;
    operation?: string | undefined;
    route?: string | undefined;
    method?: string | undefined;
    statusCode?: number | undefined;
    durationMs?: number | undefined;
    database?: string | undefined;
    dbSystem?: string | undefined;
    exceptionType?: string | undefined;
    traceId?: string | undefined;
    spanId?: string | undefined;
    attributes?: { [key: string]: string; };
}

export enum TelemetrySignal {
    Error = "Error",
    RequestDuration = "RequestDuration",
    DbDuration = "DbDuration",
}

export interface PerformanceCountersDto {
    generatedAt?: string;
    windowStart?: string;
    windowEnd?: string;
    intervalMinutes?: number;
    machine?: PerformanceCounterSourceDto | undefined;
    containers?: PerformanceCounterSourceDto[];
    series?: PerformanceCounterSeriesDto[];
    dailySummaries?: PerformanceCounterDailySummaryDto[];
}

export interface PerformanceCounterSourceDto {
    scope?: PerformanceCounterScopeDto;
    sourceId?: string;
    sourceName?: string;
    lastSeenAt?: string | undefined;
    cpuUsagePercent?: number | undefined;
    memoryUsagePercent?: number | undefined;
    memoryUsedBytes?: number | undefined;
    memoryLimitBytes?: number | undefined;
    diskUsagePercent?: number | undefined;
    diskUsedBytes?: number | undefined;
    diskTotalBytes?: number | undefined;
    networkReceiveBytesPerSecond?: number | undefined;
    networkTransmitBytesPerSecond?: number | undefined;
}

export enum PerformanceCounterScopeDto {
    Machine = "Machine",
    Container = "Container",
}

export interface PerformanceCounterSeriesDto {
    scope?: PerformanceCounterScopeDto;
    sourceId?: string;
    sourceName?: string;
    metric?: PerformanceCounterMetricDto;
    unit?: string;
    points?: PerformanceCounterPointDto[];
}

export enum PerformanceCounterMetricDto {
    CpuUsagePercent = "CpuUsagePercent",
    MemoryUsagePercent = "MemoryUsagePercent",
    DiskUsagePercent = "DiskUsagePercent",
    NetworkReceiveBytesPerSecond = "NetworkReceiveBytesPerSecond",
    NetworkTransmitBytesPerSecond = "NetworkTransmitBytesPerSecond",
}

export interface PerformanceCounterPointDto {
    timestamp?: string;
    value?: number;
}

export interface PerformanceCounterDailySummaryDto {
    day?: string;
    scope?: PerformanceCounterScopeDto;
    sourceId?: string;
    sourceName?: string;
    metric?: PerformanceCounterMetricDto;
    unit?: string;
    sampleCount?: number;
    minimum?: number;
    maximum?: number;
    average?: number;
    alertHighCount?: number;
}

export interface TelemetryEnvelope {
    dsn?: string;
    signal?: TelemetrySignal;
    occurredAt?: string;
    applicationName?: string | undefined;
    environment?: string | undefined;
    siteName?: string | undefined;
    severity?: string | undefined;
    message?: string | undefined;
    operation?: string | undefined;
    route?: string | undefined;
    method?: string | undefined;
    statusCode?: number | undefined;
    durationMs?: number | undefined;
    database?: string | undefined;
    dbSystem?: string | undefined;
    dbStatement?: string | undefined;
    exceptionType?: string | undefined;
    stackTrace?: string | undefined;
    traceId?: string | undefined;
    spanId?: string | undefined;
    attributes?: { [key: string]: string; } | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}